### ISSUE TITLE
Is this confirmed to work with Ubuntu 18.04.2 LTS?

### ISSUE THREAD

**Issue by Taddic** [SirJson/awesomewm-gnome#1]
Hello!
I tried using this repo to get Gnome and Awesome VM to work together, but when I try to actually login with the Awesome Gnome session then I am just kicked back out and nothing more happens.

I am using Ubuntu 18.04.2 LTS.
I followed the README instructions with one exception, I used apt-get to install Awesome VM instead of from github.
Any thoughts of what could be wrong? I can supply logs if needed, I just don't know which logs to attach in that case.

Best regards!

**Comment by SirJson** [comment]
Sorry for the late reply, I was looking for a way to have a spare Ubuntu System where I could reproduce the bug. 

Well that didn't work out. When I was writing the README.md I thought I will end up again with Ubuntu in the end anyways but to my surprise I didn't break my system yet. (Even tho it had to endure abuse like overwritten system libraries for a completely different CPU type)

What I didn't noticed before is Awesome 4.3 dropped. To rule out that my files are just broken with the new Awesome and GNOME 3.32 I tested it here on my Arch Linux system and everything worked out of the box. I also used the new version for a few days to see if there are any looming problems that would show up later.

Since getting any kind of VM with GUI to run on Arch Linux seems to be either buggy or just a Task I'm not ready for yet all I can offer is to look at the logs if you are still interested. 

I think it's either a dependency problem or just a rootfs / session system that works differently than I anticipated. That's unfortunately just a gut feeling, but in case it is a session problem it should be easy to fix even without Ubuntu.

**Comment by stnevans** [comment]
So I just tried this out on Ubuntu 18.04.3. The problem, at least in that case, was that the script you made is valid bash, but not valid for sh to run.
The fix for me was as simple as changing awesome-gnome to run with /bin/bash instead of /bin/sh.
My only issue is that the theme used for the terminal and chromium seems to be different (than both the theme when I use vanilla gnome and when I just use awesome).

**Comment by SirJson** [comment]
Cool thanks for testing! I will close that issue and change the line. I think my distro seems to symlink bash to sh.
