### ISSUE TITLE
how to disable gnome-flashback's root window (just use awesome's backgrounds and no desktop icons)?

### ISSUE THREAD

**Issue by ppenguin** [SirJson/awesomewm-gnome#3]
Works nicely! One question:
I want to disable the gnome root window, and use awesome's native backgrounds etc. I don't need gone's desktop icons, so best would be if I could start a complete session without gnome-flashback being visible at all.
Any idea how to do this?

**Comment by SirJson** [comment]
I think this is possible, I've worked a few months ago on a version that drops the gnome-flashback dependency and uses gnome directly. Unfortunately, this was done for a VM with a different goal which didn't end up making it. So, it never crossed my mind to back this new version up... which I regret now because it was a much nicer and simpler implementation that dropped the LOC almost in half.

In case my memory serve me right in this version the main script is the `awesome-gnome` script. Maybe it's already enough if you don't execute `gnome-flashback` by removing it from the `procs` array. It used to be in there to provide something that GNOME detects as a valid session but these days with Budgie and other GNOME-based desktops I don't think it's strictly needed anymore.

**Comment by ppenguin** [comment]
Thanks (and sorry for the late reply). I remember (I think) that removing `gnome-flashback` from `gnome-session` was the first thing I did, but I kind of like the possibilities that the gnome session gives me in terms of providing the env (I guess through the gdbus session) in terms of using `gnome-settings` and `gnome-tweaks` to set themes and start agents and such. But that actually also doesn't work perfectly, so I might reconsider...

Another (very annoying) thing I experience is that (I think) when the screensaver timeout has arrived, screen-blanking doesn't work, but the whole layout is messed up (all windows are thrown on one workspace).

**Comment by SirJson** [comment]
Yes, I remember the part that made the new version so much different from this one is setting up a gnome environment from scratch. That being said, I would have a look at the Budgie project which does exactly that to some extent. That's where I got the idea for my solution from.

The good thing is every part that would be needed is doable from a single bash script, if done in a certain way even window manager agnostic. Another source of inspiration or solutions would be other DE that base off GNOME these days like the new Ubuntu Shell, or the Pop!OS Shell.

**Comment by ppenguin** [comment]
Thanks, I'll probably try that then, since even a full gnome-shell session I have on my laptop is quite lacking in many things, such as tablet-rotate (not working, it was though with kde), automatic external display scaling on plugin, ... So it appears to be better not to be dependent on standard DE sessions anyway. 

I guess we can close this as an "issue", since the solution will be another setup altogether and not specific to this ticket. Thanks for the pointers!
